version: '2.2'

services:
  static:
    build:
      context: ./util/docker/static
    volumes:
      - ./resources/locale:/data/resources/locale
      - ./web/static:/data/web/static
      - static_node_modules:/data/web/static/node_modules

volumes:
  static_node_modules: {}
